package validate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// lockfile_content_test.go is the guard for issue #255: `civitai app validate`
// printed `✓ … is valid` and exited 0 for a project whose committed
// `package-lock.json` was 0 bytes, and the platform build failed anyway.
//
// 🔴 THE DEFECT WAS INVITED BY THE MESSAGE THAT REPLACED IT. The missing-lockfile
// error names the filename the build wants, so `touch package-lock.json` is a
// natural reading of it — and it produced a green validate in front of the
// identical opaque server-side failure. That is why the tests below assert the
// two messages are DIFFERENT, not merely that something failed.
//
// Both directions are pinned on purpose, because either half alone is satisfiable
// by a broken fix: a predicate that rejects EVERY lockfile passes every negative
// case here, and a predicate that rejects none passes every positive control. The
// positive controls are the rows that make the negatives mean anything.

// pkgJSON is the file whose presence is what makes the lockfile check fire at
// all (the recipe's `if [ -f package.json ]`).
const pkgJSON = `{"name":"lock-block","private":true}`

// npmProject validates a project with package.json + a package-lock.json holding
// exactly the given bytes, under the default (npm) build branch.
func npmProject(t *testing.T, lock string) Result {
	t.Helper()
	return project(t, lockManifest("npm run build"), map[string]string{
		"package.json":      pkgJSON,
		"package-lock.json": lock,
	})
}

// wantUnusableLockfileError asserts the finding is the EXISTS-BUT-IS-NOT-ONE
// message rather than the missing-lockfile one, and that it carries the remedy
// that does not re-invite `touch`.
func wantUnusableLockfileError(t *testing.T, res Result, lockfile, refreshCmd string, defect string) {
	t.Helper()
	if res.OK() {
		t.Fatalf("a committed %s that is not a lockfile must be a hard error, got a clean pass", lockfile)
	}
	wantLockError(t, res,
		lockfile+" is committed but "+defect,
		"not a lockfile the platform build can install from",
		// 🔴 The remedy has to say the file is GENERATED. Without this clause the
		// message is compatible with "create the file", which is the input that
		// defeated the old check.
		"GENERATED by the package manager, never hand-written and never created with `touch`",
		"delete "+lockfile,
		refreshCmd,
	)
	// It must NOT be the missing-lockfile message: an author whose file is
	// sitting right there and is told "no lockfile is committed" learns to
	// distrust the check, and `touch` looks like the fix all over again.
	msg := lockErrors(res)[0]
	for _, forbidden := range []string{"no lockfile is committed", "package.json is present but"} {
		if strings.Contains(msg, forbidden) {
			t.Errorf("the exists-but-invalid message must not reuse the MISSING message's wording %q:\n  %s",
				forbidden, msg)
		}
	}
}

// ---------------------------------------------------------------------------
// (1) The regression: a 0-byte package-lock.json. RED at base.
// ---------------------------------------------------------------------------

func TestLockfileEmptyNpmLockfileIsFatal(t *testing.T) {
	res := npmProject(t, "")
	wantUnusableLockfileError(t, res, "package-lock.json", "npm install", "it is EMPTY (0 bytes)")
	// The message must also carry npm's OWN precondition, so the author can check
	// the file against a rule rather than against our assertion. Measured on npm
	// 11.17.0: an empty package-lock.json fails `npm ci` with EUSAGE naming
	// exactly this.
	wantLockError(t, res, "lockfileVersion >= 1", "npm ci")
}

// ---------------------------------------------------------------------------
// (2) POSITIVE CONTROL — a real lockfile still passes.
//
// Without this, "reject everything" satisfies every negative case above.
// ---------------------------------------------------------------------------

func TestLockfileRealNpmLockfileStillPasses(t *testing.T) {
	res := npmProject(t, npmLockBody)
	if !res.OK() {
		t.Fatalf("a real package-lock.json must validate clean, got: %v", Messages(res.Errors))
	}
	if res.HasWarnings() {
		t.Errorf("a real package-lock.json must be warning-free, got: %v", Messages(res.Warnings))
	}
}

// ---------------------------------------------------------------------------
// (3)(4)(5) The npm content rule, in one table with both directions.
// ---------------------------------------------------------------------------

func TestLockfileNpmContentRule(t *testing.T) {
	cases := []struct {
		name string
		body string
		// defect is the clause the message must carry; "" means the body is
		// ACCEPTED (a positive control).
		defect string
		why    string
	}{
		{
			name: "a real lockfile", body: npmLockBody,
			why: "POSITIVE CONTROL: the shape `npm install` writes",
		},
		{
			name: "lockfileVersion 3 and nothing else", body: `{"lockfileVersion": 3}`,
			why: "POSITIVE CONTROL: the version key is the whole of npm's precondition; " +
				"the CLI must not invent further structure it has no authority over",
		},
		{
			name: "lockfileVersion 1, the floor", body: `{"lockfileVersion": 1}`,
			why: "POSITIVE CONTROL: npm's own bound is `>= 1`, inclusive",
		},
		{
			name: "0 bytes", body: "", defect: "it is EMPTY (0 bytes)",
			why: "issue #255 itself",
		},
		{
			name: "whitespace only", body: "  \n\t\r\n ", defect: "it is EMPTY (whitespace only)",
			why: "a file `touch`ed and then saved by an editor is whitespace, not 0 bytes — " +
				"and it is exactly as much of a lockfile",
		},
		{
			name: "valid JSON, no lockfileVersion", body: "{}\n",
			defect: `it declares no "lockfileVersion"`,
			why: "🔴 DELIBERATE: `npm ci` rejects `{}` with the SAME EUSAGE as an empty file " +
				"(\"with lockfileVersion >= 1\"), so accepting it would leave the headline " +
				"defect half-open — `echo '{}' > package-lock.json` for `touch`",
		},
		{
			name: "valid JSON object with other keys but no version", body: `{"name":"x","packages":{}}`,
			defect: `it declares no "lockfileVersion"`,
			why:    "same rule; a plausible-looking hand-written file is still not a lockfile",
		},
		{
			name: "not JSON at all", body: "lockfileVersion: 3\n",
			defect: "it does not parse as a JSON object",
			why:    "a YAML body under the npm filename — the mixed-package-manager mistake, in one file",
		},
		{
			name: "a JSON ARRAY", body: `[{"lockfileVersion": 3}]`,
			defect: "it does not parse as a JSON object",
			why: "decoding into `any` would accept this; a lockfile is an OBJECT, and the " +
				"version key of an element is not the document's",
		},
		{
			name: "lockfileVersion as a string", body: `{"lockfileVersion": "3"}`,
			defect: `its "lockfileVersion" is not a number`,
			why: "npm writes a number. Accepting a string would be the CLI inventing a rule " +
				"the platform does not have — see the residual in the doc comment",
		},
		{
			name: "lockfileVersion 0", body: `{"lockfileVersion": 0}`,
			defect: `its "lockfileVersion" is below 1`,
			why:    "npm's bound is `>= 1`; 0 is the pre-v5 sentinel and `npm ci` refuses it",
		},
	}

	var accepted, rejected int
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			res := npmProject(t, tc.body)
			if tc.defect == "" {
				if !res.OK() {
					t.Fatalf("this body must be ACCEPTED (%s), got: %v", tc.why, Messages(res.Errors))
				}
				return
			}
			wantUnusableLockfileError(t, res, "package-lock.json", "npm install", tc.defect)
		})
		if tc.defect == "" {
			accepted++
		} else {
			rejected++
		}
	}

	// Count floors on the table itself. A table that drifted to all-negative
	// would be satisfied by "reject everything", and one that drifted to
	// all-positive by "accept everything"; either reads as a serene pass.
	if accepted < 3 {
		t.Errorf("only %d ACCEPTED rows — with fewer, a predicate that rejects every "+
			"lockfile passes this whole table", accepted)
	}
	if rejected < 5 {
		t.Errorf("only %d REJECTED rows — with fewer, a predicate that accepts every "+
			"lockfile passes this whole table", rejected)
	}
}

// ---------------------------------------------------------------------------
// (6) CONTROL — the MISSING case is unchanged.
// ---------------------------------------------------------------------------

// The whole point of the new message is that it is a different one, so the old
// message must still fire, unchanged, for the case it was written for.
func TestLockfileMissingMessageIsUnchangedByTheContentCheck(t *testing.T) {
	res := project(t, lockManifest("npm run build"), map[string]string{"package.json": pkgJSON})
	if res.OK() {
		t.Fatal("package.json with no lockfile must still be a hard error")
	}
	wantLockError(t, res,
		"package.json is present but no lockfile is committed",
		"npm ci",
		"package-lock.json",
		"npm install",
	)
	// And it must NOT have acquired the new message's wording — one finding, one
	// diagnosis.
	if msg := lockErrors(res)[0]; strings.Contains(msg, "is committed but") {
		t.Errorf("the missing-lockfile message must not claim a file is committed:\n  %s", msg)
	}
}

// ---------------------------------------------------------------------------
// (7) pnpm and yarn: NON-EMPTY, and deliberately nothing more.
// ---------------------------------------------------------------------------

// The asymmetry with npm is a decision, not an omission: `pnpm-lock.yaml` would
// need a YAML parser (a new third-party dependency — "ask first" in AGENTS.md)
// and a yarn v1 `yarn.lock` carries no version key at all. "Not empty" is the
// whole of what can be said without inventing authority, and it is exactly the
// defect issue #255 reported.
func TestLockfileNonJSONManagersRejectOnlyEmptiness(t *testing.T) {
	cases := []struct {
		build      string
		lockfile   string
		refreshCmd string
	}{
		{"pnpm run build", "pnpm-lock.yaml", "pnpm install"},
		{"yarn run build", "yarn.lock", "yarn install"},
	}
	for _, tc := range cases {
		t.Run(tc.lockfile, func(t *testing.T) {
			for _, empty := range []struct{ name, body, defect string }{
				{"0 bytes", "", "it is EMPTY (0 bytes)"},
				{"whitespace only", "\n\n  \t\n", "it is EMPTY (whitespace only)"},
			} {
				t.Run(empty.name, func(t *testing.T) {
					res := project(t, lockManifest(tc.build), map[string]string{
						"package.json": pkgJSON,
						tc.lockfile:    empty.body,
					})
					wantUnusableLockfileError(t, res, tc.lockfile, tc.refreshCmd, empty.defect)
				})
			}

			// POSITIVE CONTROLS. The second is the one that pins the asymmetry:
			// a body that npm's rule would REJECT must be accepted here, or the
			// npm rule has silently leaked onto every package manager.
			for _, ok := range []struct{ name, body string }{
				{"a real lockfile", lockBody(tc.lockfile)},
				{"a body npm's rule would reject", "{}\n"},
				{"anything non-blank at all", "x"},
			} {
				t.Run("accepts "+ok.name, func(t *testing.T) {
					res := project(t, lockManifest(tc.build), map[string]string{
						"package.json": pkgJSON,
						tc.lockfile:    ok.body,
					})
					if !res.OK() {
						t.Fatalf("%s must accept any non-empty body, got: %v", tc.lockfile, Messages(res.Errors))
					}
				})
			}
		})
	}
}

// ---------------------------------------------------------------------------
// (8) CONTROL — a static app is never flagged, whatever the lockfile state.
// ---------------------------------------------------------------------------

// The recipe's `if [ -f package.json ]` guard is what makes a static block skip
// the install step entirely. It must keep deciding this BEFORE any content is
// read: an empty lockfile in a tree that never installs is inert, and flagging
// it would be a hard error on a project the platform builds fine.
func TestLockfileContentCheckNeverFiresWithoutPackageJSON(t *testing.T) {
	for _, body := range []string{"", "   \n", "{}\n", "not json", npmLockBody} {
		res := project(t, lockManifest(""), map[string]string{"package-lock.json": body})
		if !res.OK() {
			t.Errorf("a static app (no package.json) must never be flagged for its lockfile "+
				"content (%q), got: %v", body, Messages(res.Errors))
		}
	}
}

// ---------------------------------------------------------------------------
// (9) UNOBSERVABLE -> the old presence-only PASS, never an error.
// ---------------------------------------------------------------------------

// 🔴 This check is FATAL, so a state we could not read must degrade to what the
// check did before rather than manufacture a hard error out of a gap
// (AGENTS.md item 18). The size cap is the observable half of that: over it, the
// file is not read at all.
//
// The sub-cap row is the CONTROL that makes the over-cap row mean something. The
// two files hold the SAME bytes and differ only in length, so a pass at 64 MiB+1
// is attributable to the cap and to nothing else — without it, "the big file
// passed" is equally consistent with a predicate that accepts everything.
func TestLockfileOverTheSizeCapDegradesToPresenceOnly(t *testing.T) {
	// A sparse file: Truncate reports the size without writing 64 MiB.
	sparse := func(t *testing.T, dir string, size int64) {
		t.Helper()
		f, err := os.Create(filepath.Join(dir, "package-lock.json"))
		if err != nil {
			t.Fatal(err)
		}
		defer f.Close()
		if err := f.Truncate(size); err != nil {
			t.Skipf("cannot create a sparse file here: %v", err)
		}
	}
	run := func(t *testing.T, size int64) Result {
		t.Helper()
		dir := t.TempDir()
		for name, body := range map[string]string{
			"block.manifest.json": lockManifest("npm run build"),
			"package.json":        pkgJSON,
		} {
			if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600); err != nil {
				t.Fatal(err)
			}
		}
		sparse(t, dir, size)
		res, err := Dir(dir)
		if err != nil {
			t.Fatalf("Dir: %v", err)
		}
		return res
	}

	// CONTROL: the same NUL bytes, comfortably under the cap, ARE read and ARE
	// rejected. If this passes, the row below proves nothing.
	if res := run(t, 4096); res.OK() {
		t.Fatal("control: a sub-cap file of NUL bytes is not JSON and must be rejected — " +
			"the over-cap assertion below is vacuous without this")
	}

	if res := run(t, maxLockfileBytes+1); !res.OK() {
		t.Errorf("a lockfile over the %d-byte cap is UNOBSERVABLE, so the check must fall back "+
			"to the presence-only pass rather than manufacture a hard error from a gap; got: %v",
			int64(maxLockfileBytes), Messages(res.Errors))
	}
}

// An unreadable lockfile is the other unobservable state. Same doctrine: we did
// not look, so we say nothing.
func TestLockfileUnreadableDegradesToPresenceOnly(t *testing.T) {
	dir := t.TempDir()
	for name, body := range map[string]string{
		"block.manifest.json": lockManifest("npm run build"),
		"package.json":        pkgJSON,
	} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	lock := filepath.Join(dir, "package-lock.json")
	// Content that WOULD be rejected, so a pass can only come from the read
	// failing — not from the bytes being acceptable.
	if err := os.WriteFile(lock, []byte(""), 0o000); err != nil {
		t.Fatal(err)
	}
	if _, err := os.ReadFile(lock); err == nil {
		t.Skip("this process can read a mode-000 file (running as root?), so there is no " +
			"unreadable state to observe here")
	}

	res, err := Dir(dir)
	if err != nil {
		t.Fatalf("Dir: %v", err)
	}
	if !res.OK() {
		t.Errorf("an unreadable lockfile is UNOBSERVABLE — the check must degrade to the "+
			"presence-only pass, not block a submit on a gap; got: %v", Messages(res.Errors))
	}
}

// ---------------------------------------------------------------------------
// The Lstat/IsRegular gate must stay IN FRONT of the read.
// ---------------------------------------------------------------------------

// 🔴 regularFileExists mirrors pkgzip.Build, which skips every non-regular entry,
// so a SYMLINKED lockfile is dropped from the submitted bundle. os.ReadFile
// FOLLOWS symlinks — so a content check that read first (or read independently)
// would vouch for bytes the bundle does not carry, and the platform build would
// hard-fail behind a green validate. TestLockfileSymlinkedLockfileIsNotAccepted
// pins the verdict; this pins the ORDER, by pointing the symlink at a VALID
// lockfile. Only a check that reads through the link can pass it.
func TestLockfileSymlinkToAValidLockfileIsStillAbsent(t *testing.T) {
	dir := t.TempDir()
	for name, body := range map[string]string{
		"block.manifest.json": lockManifest("npm run build"),
		"package.json":        pkgJSON,
	} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	outside := filepath.Join(t.TempDir(), "package-lock.json")
	if err := os.WriteFile(outside, []byte(npmLockBody), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(dir, "package-lock.json")); err != nil {
		t.Skipf("cannot create a symlink here: %v", err)
	}

	res, err := Dir(dir)
	if err != nil {
		t.Fatalf("Dir: %v", err)
	}
	if res.OK() {
		t.Fatal("a symlinked lockfile is dropped from the bundle, so even a perfectly valid " +
			"one must read as ABSENT — the Lstat/IsRegular gate has to run before the read")
	}
	wantLockError(t, res, "no lockfile is committed")
}

// ---------------------------------------------------------------------------
// Scope: only the REQUIRED lockfile's content is judged.
// ---------------------------------------------------------------------------

// A foreign lockfile is reported for what it is — evidence of which package
// manager the project really uses — and that reading does not depend on its
// bytes. Judging it too would stack a second, confusing finding on top of the
// real one, exactly as deriving a package manager from a disallowed buildCommand
// would.
func TestLockfileContentOfAForeignLockfileIsNotJudged(t *testing.T) {
	res := project(t, lockManifest("pnpm run build"), map[string]string{
		"package.json":      pkgJSON,
		"pnpm-lock.yaml":    lockBody("pnpm-lock.yaml"),
		"package-lock.json": "", // empty, and irrelevant: pnpm is what installs
	})
	if !res.OK() {
		t.Fatalf("an empty FOREIGN lockfile must not be a hard error: %v", Messages(res.Errors))
	}
	// It is still reported as an extra lockfile, unchanged.
	joined := strings.Join(Messages(res.Warnings), "\n")
	if !strings.Contains(joined, "more than one lockfile is committed") {
		t.Errorf("the extra-lockfile advisory must be unchanged:\n%s", joined)
	}
}
