package main

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"
	"time"
)

// 🔴 A DETECTOR THAT HAS NEVER BEEN SHOWN TO FIRE IS NOT A DETECTOR.
//
// The centre of this file is TestTheStateThatBrokeBrewOn20260809GoesRed, which
// reconstructs the EXACT state that shipped a broken `brew install` to every
// user for ~2 hours: the tap's cask naming 0.1.91 while the newest publicly
// downloadable archives were 0.1.90's, because the v0.1.91 release was still a
// draft. Nothing is un-published to produce it — the fixture is two httptest
// servers, and the code under test is the real `checker`, driven over real HTTP.
//
// Every other test in this file exists to stop that one being satisfied for the
// wrong reason: a checker that refuses everything would pass it and fail the
// green cases, a checker wired to nothing would pass the green cases and fail
// it, and a checker that reads the release API instead of the archive would pass
// BOTH while being blind to the incident (see assertNoAuth).

// caskFixture renders a cask in the shape goreleaser actually emits — `version`
// stanza plus one `url` per OS/arch with `#{version}` interpolation — against a
// given release host.
func caskFixture(version, releaseHost string) string {
	var b strings.Builder
	b.WriteString("# This file was generated by GoReleaser. DO NOT EDIT.\n")
	b.WriteString("cask \"civitai\" do\n")
	fmt.Fprintf(&b, "  version %q\n\n", version)
	for _, t := range []string{"darwin_amd64", "darwin_arm64", "linux_amd64", "linux_arm64"} {
		fmt.Fprintf(&b, "      sha256 \"deadbeef\"\n")
		fmt.Fprintf(&b, "      url \"%s/civitai/cli/releases/download/v#{version}/civitai_#{version}_%s.tar.gz\"\n", releaseHost, t)
	}
	b.WriteString("  binary \"civitai\"\nend\n")
	return b.String()
}

// recorder captures what each request carried, so a test can assert on the
// SHAPE of the request and not merely on the answer.
type recorder struct {
	mu   sync.Mutex
	auth map[string][]string // path -> Authorization header per request
	hits map[string]int
}

func newRecorder() *recorder {
	return &recorder{auth: map[string][]string{}, hits: map[string]int{}}
}

func (r *recorder) record(req *http.Request) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.auth[req.URL.Path] = append(r.auth[req.URL.Path], req.Header.Get("Authorization"))
	r.hits[req.URL.Path]++
}

func (r *recorder) authFor(prefix string) []string {
	r.mu.Lock()
	defer r.mu.Unlock()
	var out []string
	for p, vals := range r.auth {
		if strings.HasPrefix(p, prefix) {
			out = append(out, vals...)
		}
	}
	return out
}

// world is a fixture pipeline: a tap serving one cask, and a release host that
// serves archives for exactly the versions that have been PUBLISHED.
type world struct {
	tap       *httptest.Server
	releases  *httptest.Server
	api       *httptest.Server
	rec       *recorder
	caskBody  string
	published map[string]bool // version -> archives are publicly downloadable
	latestTag string
}

func newWorld(t *testing.T, caskVersion string, published []string, latestTag string) *world {
	t.Helper()
	w := &world{rec: newRecorder(), published: map[string]bool{}, latestTag: latestTag}
	for _, v := range published {
		w.published[v] = true
	}

	w.releases = httptest.NewServer(http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		w.rec.record(req)
		// /civitai/cli/releases/download/v<ver>/civitai_<ver>_<t>.tar.gz
		parts := strings.Split(strings.Trim(req.URL.Path, "/"), "/")
		if len(parts) < 5 {
			rw.WriteHeader(http.StatusNotFound)
			return
		}
		ver := strings.TrimPrefix(parts[len(parts)-2], "v")
		if !w.published[ver] {
			// Exactly what github.com answers for an asset that belongs to a
			// draft release, or to no release at all.
			rw.WriteHeader(http.StatusNotFound)
			return
		}
		rw.WriteHeader(http.StatusOK)
		_, _ = rw.Write([]byte("tarball"))
	}))
	t.Cleanup(w.releases.Close)

	w.caskBody = caskFixture(caskVersion, w.releases.URL)
	w.tap = httptest.NewServer(http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		w.rec.record(req)
		rw.WriteHeader(http.StatusOK)
		_, _ = rw.Write([]byte(w.caskBody))
	}))
	t.Cleanup(w.tap.Close)

	w.api = httptest.NewServer(http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		w.rec.record(req)
		rw.Header().Set("Content-Type", "application/json")
		fmt.Fprintf(rw, `{"tag_name":%q,"draft":false,"prerelease":false}`, w.latestTag)
	}))
	t.Cleanup(w.api.Close)
	return w
}

func (w *world) checker() *checker {
	return &checker{
		caskURL:   w.tap.URL + "/Casks/civitai.rb",
		latestURL: w.api.URL + "/repos/civitai/cli/releases/latest",
		apiToken:  "fixture-token",
		client:    &http.Client{Timeout: 10 * time.Second},
	}
}

func run(t *testing.T, c *checker) (*report, error) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	return c.check(ctx)
}

// TestTheStateThatBrokeBrewOn20260809GoesRed is the proven-failure evidence.
//
// Cask 0.1.91 / newest publicly downloadable 0.1.90 — the v0.1.91 release
// existed but was a DRAFT, so its assets 404 for everyone. Measured on the live
// pipeline that day by the maintainer:
//
//	cask Casks/civitai.rb                                        version "0.1.91"
//	GET .../download/v0.1.91/civitai_0.1.91_linux_amd64.tar.gz    404
//	GET .../download/v0.1.90/civitai_0.1.90_linux_amd64.tar.gz    200
//	npm @civitai/cli                                              0.1.90 (correct)
//
// Mutation-measured, each mutation checksum-gated so an edit that failed to
// apply is reported broken rather than read as a survivor. Leaf `--- FAIL` lines
// counted from `go test -v` output, never an exit code; base is 11 `--- PASS`:
//
//	probe.ok() accepts any status          3  (this test, the credential guard, the dead-diagnostic guard)
//	archive probe carries the token        1
//	the zero-URL control removed           1
//	unreachable tap treated as clean       3
//	errUnreachableTap wrapped %w -> %v     3
//
// The first row is the one that matters here: this test's verdict depends on the
// HTTP status the archive actually returned, and on nothing else.
func TestTheStateThatBrokeBrewOn20260809GoesRed(t *testing.T) {
	w := newWorld(t, "0.1.91", []string{"0.1.90"}, "v0.1.90")

	rep, err := run(t, w.checker())
	if err == nil {
		t.Fatalf("the 2026-08-09 breakage passed this check.\n"+
			"Cask names 0.1.91 while only 0.1.90 is downloadable — `brew install` is broken in this state, and a detector that\n"+
			"cannot see it is not a detector. report=%+v", rep)
	}

	// The message has to carry the diagnosis, not just a verdict: an operator
	// reading it at 2am needs both versions and the status code.
	for _, want := range []string{"0.1.91", "v0.1.90", "404"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("failure message does not mention %q, so it does not say what is wrong:\n%v", want, err)
		}
	}
	// All four archives are missing, and the count has to be honest.
	if !strings.Contains(err.Error(), "4 of its 4") {
		t.Errorf("failure message should account for every URL it probed:\n%v", err)
	}
	if rep == nil || len(rep.probes) != 4 {
		t.Fatalf("want 4 probes recorded, got %+v", rep)
	}
}

// TestThePublishedStateIsGreen is the other half. Without it, "the red fixture
// went red" is equally consistent with a checker that refuses everything.
func TestThePublishedStateIsGreen(t *testing.T) {
	w := newWorld(t, "0.1.91", []string{"0.1.90", "0.1.91"}, "v0.1.91")

	rep, err := run(t, w.checker())
	if err != nil {
		t.Fatalf("a correctly published pipeline must be green: %v", err)
	}
	if len(rep.probes) != 4 {
		t.Fatalf("want 4 archive probes, got %d — a green verdict reached by asking nothing is the reassuring zero", len(rep.probes))
	}
	for _, p := range rep.probes {
		if !p.ok() {
			t.Errorf("probe %s should be ok", p)
		}
	}
}

// TestACaskLaggingThePublishedReleaseIsDeliberatelyGREEN pins a NON-decision.
//
// Between a tag push and the maintainer publishing the draft, the cask correctly
// still names the previous version. That is the whole point of the new ordering,
// so it must not be a finding — a check that reddened here would be red for
// doing the right thing, and a permanently-red gate trains everyone to ignore it.
func TestACaskLaggingThePublishedReleaseIsDeliberatelyGREEN(t *testing.T) {
	w := newWorld(t, "0.1.90", []string{"0.1.90", "0.1.91"}, "v0.1.91")

	rep, err := run(t, w.checker())
	if err != nil {
		t.Fatalf("a cask lagging the newest published release is not a violation — 0.1.90 is downloadable, nobody is broken: %v", err)
	}
	if rep.caskVersion != "0.1.90" {
		t.Fatalf("read cask version %q, want 0.1.90", rep.caskVersion)
	}
}

// TestAnUnreachableTapIsLoudNotClean — "we could not ask" must never look like
// "we asked and it was fine".
func TestAnUnreachableTapIsLoudNotClean(t *testing.T) {
	t.Run("connection refused", func(t *testing.T) {
		w := newWorld(t, "0.1.91", []string{"0.1.91"}, "v0.1.91")
		c := w.checker()
		w.tap.Close() // the tap is now unreachable; everything else is healthy
		_, err := run(t, c)
		if err == nil {
			t.Fatal("an unreachable tap reported clean — the check would silently no-op whenever the tap is down")
		}
		if !errors.Is(err, errUnreachableTap) {
			t.Errorf("want errUnreachableTap, got %v", err)
		}
	})

	t.Run("tap answers non-200", func(t *testing.T) {
		srv := httptest.NewServer(http.HandlerFunc(func(rw http.ResponseWriter, _ *http.Request) {
			rw.WriteHeader(http.StatusServiceUnavailable)
		}))
		t.Cleanup(srv.Close)
		c := &checker{caskURL: srv.URL, latestURL: srv.URL, client: &http.Client{Timeout: 5 * time.Second}}
		_, err := run(t, c)
		if !errors.Is(err, errUnreachableTap) {
			t.Fatalf("a 503 from the tap must be loud, got %v", err)
		}
		if !strings.Contains(err.Error(), "503") {
			t.Errorf("the status code is the diagnosis and must appear: %v", err)
		}
	})
}

// TestACaskWithNoArchiveURLsIsAControlFailure is the positive control on the
// probe loop itself: zero URLs means zero questions asked, and zero failures is
// then guaranteed regardless of the state of the world.
func TestACaskWithNoArchiveURLsIsAControlFailure(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(rw http.ResponseWriter, _ *http.Request) {
		_, _ = rw.Write([]byte("cask \"civitai\" do\n  version \"0.1.91\"\nend\n"))
	}))
	t.Cleanup(srv.Close)
	c := &checker{caskURL: srv.URL, latestURL: srv.URL, client: &http.Client{Timeout: 5 * time.Second}}

	_, err := run(t, c)
	if !errors.Is(err, errNothingChecked) {
		t.Fatalf("a cask this check cannot read URLs out of must fail loudly, got %v", err)
	}
}

// TestACaskWithNoVersionStanzaIsLoud — same shape, one field up.
func TestACaskWithNoVersionStanzaIsLoud(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(rw http.ResponseWriter, _ *http.Request) {
		_, _ = rw.Write([]byte("cask \"civitai\" do\nend\n"))
	}))
	t.Cleanup(srv.Close)
	c := &checker{caskURL: srv.URL, latestURL: srv.URL, client: &http.Client{Timeout: 5 * time.Second}}

	if _, err := run(t, c); err == nil {
		t.Fatal("a cask with no version stanza reported clean")
	}
}

// TestArchiveProbesCarryNoCredential is the reason this command exists at all.
//
// 🔴 A DRAFT RELEASE IS VISIBLE TO ANY REPO TOKEN, AND CI ALWAYS HAS ONE. If the
// archive request carried Authorization, the check could be answered by the very
// object whose invisibility to users IS the outage. So the archive and cask
// requests must go out as a stranger — and the assertion is only meaningful
// paired with the positive control below, that the token plumbing is live and
// DOES attach on the releases-API call. Without that control, "no Authorization
// anywhere" is equally satisfied by a checker holding no token at all.
func TestArchiveProbesCarryNoCredential(t *testing.T) {
	w := newWorld(t, "0.1.91", []string{"0.1.90"}, "v0.1.90") // red, so the API path is exercised too

	if _, err := run(t, w.checker()); err == nil {
		t.Fatal("PREMISE BROKEN: this fixture must be the failing one, or the releases-API call below is never made")
	}

	for _, got := range w.rec.authFor("/civitai/cli/releases/download/") {
		if got != "" {
			t.Errorf("an archive probe carried Authorization %q — it must ask exactly what an unauthenticated `brew install` asks", got)
		}
	}
	for _, got := range w.rec.authFor("/Casks/") {
		if got != "" {
			t.Errorf("the cask fetch carried Authorization %q; the tap is public and brew reads it anonymously", got)
		}
	}

	api := w.rec.authFor("/repos/civitai/cli/releases/latest")
	if len(api) == 0 {
		t.Fatal("POSITIVE CONTROL failed: the releases API was never called, so 'no Authorization on the archive' is vacuous")
	}
	for _, got := range api {
		if got != "Bearer fixture-token" {
			t.Errorf("the releases API call should carry the token (it buys rate limit); got %q", got)
		}
	}
}

// TestTheDiagnosticLookupCannotTurnAHealthyPipelineRed — the releases API is not
// the invariant, so its failure must not become one.
func TestTheDiagnosticLookupCannotTurnAHealthyPipelineRed(t *testing.T) {
	w := newWorld(t, "0.1.91", []string{"0.1.91"}, "v0.1.91")
	c := w.checker()
	c.latestURL = "http://127.0.0.1:1/nope" // guaranteed refused

	if _, err := run(t, c); err != nil {
		t.Fatalf("a dead releases API must not fail a pipeline whose archives are all downloadable: %v", err)
	}
}

// TestADeadDiagnosticLookupStillReportsTheRealFinding — and it must not swallow
// one either. The finding stands on the HTTP probes alone.
func TestADeadDiagnosticLookupStillReportsTheRealFinding(t *testing.T) {
	w := newWorld(t, "0.1.91", []string{"0.1.90"}, "v0.1.90")
	c := w.checker()
	c.latestURL = "http://127.0.0.1:1/nope"

	_, err := run(t, c)
	if err == nil {
		t.Fatal("the broken state went unreported because the diagnostic lookup failed")
	}
	if !strings.Contains(err.Error(), "0.1.91") || !strings.Contains(err.Error(), "unknown") {
		t.Errorf("want the finding plus an explicit 'unknown' for the un-readable diagnostic, got:\n%v", err)
	}
}
